#!/bin/bash
#
# ircDDBGateway startup script
# John Hays (K7VE) - john@hays.org
# Hans-J. Barthen (DL5DI) - dl5di@gmx.de
#
# chkconfig: 2345 99 01
# description: Starts the G4KLX ircDDBGateway
# config: /etc/sysconfig/ircddbgateway
#


if [ $UID -ne 0 ]; then
	echo
	     echo "ERROR:  This script must be run as the root user!"
	     echo "        Please use 'su' or log in as root and try again."
	     echo
	     exit 1
 fi
# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
[ -r /etc/sysconfig/network ] && . /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 1

# Source the ircddbgateway configuration
[ -f /etc/sysconfig/ircddbgateway ] && . /etc/sysconfig/ircddbgateway

start() {

    echo -n "Starting ircddbgateway:"
    daemon --pidfile /var/run/ircddbgateway.pid $IRCDDBGATEWAY_PATH $IRCDDBGATEWAY_OPTIONS 
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/ircddbgateway
    pidofproc $IRCDDBGATEWAY_PATH > /var/run/ircddbgateway.pid
    echo
    sleep 2
    # create a watchdog entry to the crontab
    echo "*/10 * * * * root ps aux | grep $IRCDDBGATEWAY_PATH | grep -vq grep || /etc/init.d/ircddbgateway start" > /etc/cron.d/ircddbgateway
    if [ "${IRCDDBGATEWAY_DDENABLED}" = "yes" ];then
	echo " - configure dd-mode network device $IRCDDBGATEWAY_DDDEV "
        sleep 15
	/sbin/ifconfig $IRCDDBGATEWAY_DDDEV $IRCDDBGATEWAY_DDIP netmask $IRCDDBGATEWAY_DDMASK
        echo 1 > /proc/sys/net/ipv4/ip_forward
	if [ "${IRCDDBGATEWAY_DDDHCP}" = "yes" ];then
	    echo " - start dhcpd "
            /sbin/service dhcpd start
	fi
    fi
}

stop() {
    
    echo -n "Stopping ircddbgateway "
    if [ "${IRCDDBGATEWAY_DDENABLED}" = "yes" -a  "${IRCDDBGATEWAY_DDDHCP}" = "yes" ]; then
        echo " - dhcp for dd-mode is enabled, stop it "
        /sbin/service dhcpd stop
        sleep 15
    fi                    
    killproc $IRCDDBGATEWAY_PATH
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/ircddbgateway
    # remove watchdog entry from crontab
    rm -f /etc/cron.d/ircddbgateway                
    echo

}

restart() {
    stop
    sleep 2
    if [ "${IRCDDBGATEWAY_DDDHCP}" = "yes" ];then
	sleep 15
    fi
    start
}	

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    status)
	status $IRCDDBGATEWAY_PATH
	;;
    *)
	echo -e $"\nUsage: \n\t$0 {option}"
	echo -e "\n\tOptions:\n"
	echo -e "\trestart       - restarts ircddbgateway\n"
	echo -e "\tstart         - starts ircddbgateway\n"
	echo -e "\tstatus        - display status\n"
	echo -e "\tstop          - stops ircddbgateway\n"
	echo -e "\n"
	exit 1
esac

exit $RETVAL
