#!/bin/bash
#
# Timeserver startup script
# John Hays (K7VE) - john@hays.org
# Hans-J. Barthen (DL5DI) - dl5di@gmx.de
#
# chkconfig: 2345 99 01
# description: Starts the G4KLX Timeserver
# config: /etc/sysconfig/timeserver
#


if [ $UID -ne 0 ]; then
	echo
	     echo "ERROR:  This script must be run as the root user!"
	     echo "        Please use 'su' or log in as root and try again."
	     echo
	     exit 1
 fi
# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
[ -r /etc/sysconfig/network ] && . /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 1

# Source the timeserver configuration
[ -f /etc/sysconfig/timeserver ] && . /etc/sysconfig/timeserver

start() {

    echo -n "Starting timeserver:"
    daemon --pidfile /var/run/timeserver.pid $TIMESERVER_PATH $TIMESERVER_OPTIONS 
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/timeserver
    pidofproc $TIMESERVER_PATH > /var/run/timeserver.pid
    echo
}

stop() {
    
    echo -n "Stopping timeserver "
    killproc $TIMESERVER_PATH
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/timeserver
    echo

}

restart() {
    stop
    start
}	

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    status)
	status $TIMESERVER_PATH
	;;
    *)
	echo -e $"\nUsage: \n\t$0 {option}"
	echo -e "\n\tOptions:\n"
	echo -e "\trestart       - restarts timeserver\n"
	echo -e "\tstart         - starts timeserver\n"
	echo -e "\tstatus        - display status\n"
	echo -e "\tstop          - stops timeserver\n"
	echo -e "\n"
	exit 1
esac

exit $RETVAL
