#!/bin/bash
#
# DCSGateway startup script
# Hans-J. Barthen (DL5DI) - dl5di@darc.de
#
# chkconfig: 345 99 01
# description: Starts the G4KLX DCSGateway
# config: /etc/sysconfig/dcsrepeater
#


if [ $UID -ne 0 ]; then
	echo
	     echo "ERROR:  This script must be run as the root user!"
	     echo "        Please use 'su' or log in as root and try again."
	     echo
	     exit 1
fi

# Source function library.
if [ -f /etc/init.d/functions ] ; then
    . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
    . /etc/rc.d/init.d/functions
else
    exit 1
fi

# Source networking configuration.
[ -r /etc/sysconfig/network ] && . /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 1

# Source the dcsgateway configuration
[ -f /etc/sysconfig/dcsgateway ] && . /etc/sysconfig/dcsgateway

RETVAL=0

start() {

    echo -n "Starting dcsgateway:"
    daemon --pidfile /var/run/dcsgateway.pid $DCSGATEWAY_PATH $DCSGATEWAY_OPTIONS &
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/dcsgateway
    pidofproc $DCSGATEWAY_PATH > /var/run/dcsgateway.pid
    echo
    return $RETVAL
}

stop() {
    
    echo -n "Stopping dcsgateway "
    killproc $DCSGATEWAY_PATH
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/dcsgateway
    echo
    return $RETVAL
}

restart() {
    stop
    sleep 2
    start
}	

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    status)
	status $DCSGATEWAY_PATH
	;;
    *)
	echo -e $"\nUsage: \n\t$0 {option}"
	echo -e "\n\tOptions:\n"
	echo -e "\trestart       - restarts dcsgateway\n"
	echo -e "\tstart         - starts dcsgateway\n"
	echo -e "\tstatus        - display status\n"
	echo -e "\tstop          - stops dcsgateway\n"
	echo -e "\n"
	exit 1
esac

exit $RETVAL
