#!/bin/bash
#
# DExtraGateway startup script
# John Hays (K7VE) - john@hays.org
# Hans-J. Barthen (DL5DI) - dl5di@darc.de
#
# chkconfig: 345 99 01
# description: Starts the G4KLX DExtraGateway
# config: /etc/sysconfig/dextrarepeater
#


if [ $UID -ne 0 ]; then
	echo
	     echo "ERROR:  This script must be run as the root user!"
	     echo "        Please use 'su' or log in as root and try again."
	     echo
	     exit 1
fi

# Source function library.
if [ -f /etc/init.d/functions ] ; then
    . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
    . /etc/rc.d/init.d/functions
else
    exit 1
fi

# Source networking configuration.
[ -r /etc/sysconfig/network ] && . /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 1

# Source the dextragateway configuration
[ -f /etc/sysconfig/dextragateway ] && . /etc/sysconfig/dextragateway

RETVAL=0

start() {

    echo -n "Starting dextragateway:"
    daemon --pidfile /var/run/dextragateway.pid $DEXTRAGATEWAY_PATH $DEXTRAGATEWAY_OPTIONS &
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/dextragateway
    pidofproc $DEXTRAGATEWAY_PATH > /var/run/dextragateway.pid
    echo
    return $RETVAL
}

stop() {
    
    echo -n "Stopping dextragateway "
    killproc $DEXTRAGATEWAY_PATH
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/dextragateway
    echo
    return $RETVAL
}

restart() {
    stop
    sleep 2
    start
}	

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    status)
	status $DEXTRAGATEWAY_PATH
	;;
    *)
	echo -e $"\nUsage: \n\t$0 {option}"
	echo -e "\n\tOptions:\n"
	echo -e "\trestart       - restarts dextragateway\n"
	echo -e "\tstart         - starts dextragateway\n"
	echo -e "\tstatus        - display status\n"
	echo -e "\tstop          - stops dextragateway\n"
	echo -e "\n"
	exit 1
esac

exit $RETVAL
